# ----------------------------------------------------------
-- Billing Address
# ----------------------------------------------------------

INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (1,1,"Laos","6541 Auctor. Avenue","Stonewall","Manitoba","613102");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (2,2,"Poland","7138 Duis St.","Argyle","Nova Scotia","69-560");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (3,3,"Israel","P.O. Box 375, 5193 Porttitor Avenue","Kakisa","NT","384932");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (4,4,"Mauritius","Ap #615-6432 Lacinia Av.","Charlottetown","PE","20413");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (5,5,"Guadeloupe","380-6406 Sed Road","Vancouver","BC","30015");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (6,6,"Armenia","Ap #848-1006 Nullam Avenue","Strathcona County","Alberta","35049");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (7,7,"Tuvalu","P.O. Box 804, 2900 Leo. Ave","Fredericton","NB","838105");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (8,8,"Ghana","521-1969 Semper, St.","East Gwillimbury","Ontario","29897");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (9,9,"Slovakia","1169 Nec, Ave","Edmundston","New Brunswick","112246");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (10,10,"Indonesia","316-1561 Egestas. Road","Montague","Prince Edward Island","0916 UU");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (11,11,"Holy See (Vatican City State)","881-7068 Est Rd.","Whitehorse","YT","P71 6TX");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (12,12,"Virgin Islands, British","P.O. Box 951, 1069 Venenatis Avenue","Lang","SK","68976");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (13,13,"Congo, the Democratic Republic of the","9302 Phasellus Rd.","Stratford","Prince Edward Island","5491");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (14,14,"Kyrgyzstan","2158 Penatibus Av.","Paradise","NL","79413");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (15,15,"Serbia","Ap #446-804 Enim Road","Minitonas","MB","42079");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (16,16,"Tuvalu","Ap #198-1536 Mi Rd.","Inuvik","NT","18817");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (17,17,"Andorra","Ap #439-5167 In Avenue","McCallum","Newfoundland and Labrador","45314");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (18,18,"Puerto Rico","7571 Hendrerit. St.","Iqaluit","Nunavut","5445");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (19,19,"Comoros","173-4592 Nulla Rd.","Berwick","NS","71668");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (20,20,"France","9940 Hendrerit Avenue","Fogo","NL","2334");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (21,21,"Thailand","5782 Ultrices, Road","Arviat","Nunavut","B5 5MB");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (22,22,"Viet Nam","527-4845 Sed Road","Lang","SK","31324");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (23,23,"Korea, North","520-8477 Maecenas Street","Wilmont","ON","879369");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (24,24,"American Samoa","898-3742 Phasellus St.","Richmond","QC","J1P 2V1");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (25,25,"Bermuda","715-4024 Lacinia Rd.","Winnipeg","MB","3559 VZ");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (26,26,"Denmark","531-4366 Nulla St.","Matagami","QC","2235");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (27,27,"Brazil","Ap #265-6088 Feugiat Rd.","Lourdes","Manitoba","88141-38313");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (28,28,"Kuwait","8700 Ante Rd.","Dieppe","NB","860777");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (29,29,"Nicaragua","Ap #389-1647 Felis Street","Canora","Saskatchewan","8436");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (30,30,"Cook Islands","P.O. Box 568, 2381 Velit. St.","Canora","Saskatchewan","3020");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (31,31,"Romania","Ap #763-8780 Enim. Rd.","Whitehorse","YT","22308");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (32,32,"Jamaica","Ap #444-2509 Donec Street","Weyburn","SK","00084");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (33,33,"Nauru","P.O. Box 792, 5412 Cras Av.","Iqaluit","Nunavut","839881");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (34,34,"Zambia","Ap #736-8262 Vehicula. Rd.","Langenburg","SK","51345");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (35,35,"Reunion","764-9317 Mauris St.","Pangnirtung","Nunavut","62114");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (36,36,"Malaysia","7332 Adipiscing Rd.","Maple Creek","Saskatchewan","04128");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (37,37,"Uruguay","258-2777 Amet, Ave","Regina","SK","29349");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (38,38,"Liechtenstein","Ap #376-1474 Mauris St.","Fortune","Newfoundland and Labrador","11664");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (39,39,"Puerto Rico","572-9297 Mollis St.","Baddeck","NS","53286");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (40,40,"Costa Rica","Ap #329-7645 Fringilla, Av.","Welland","ON","848270");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (41,41,"Egypt","Ap #661-8978 Cursus Street","Kent","BC","71517");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (42,42,"Estonia","568-1744 Suscipit, Rd.","Arviat","Nunavut","87612");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (43,43,"Malaysia","Ap #618-1624 Nibh. St.","St. Catharines","Ontario","836930");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (44,44,"Antarctica","P.O. Box 786, 7107 Mauris Street","Cambridge Bay","Nunavut","5082 GK");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (45,45,"Brazil","680-9743 Sagittis Rd.","Penticton","BC","69887-38017");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (46,46,"Virgin Islands, British","242-8761 Molestie Av.","McCallum","Newfoundland and Labrador","543723");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (47,47,"Djibouti","312 Pharetra Rd.","Lang","SK","18579");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (48,48,"Pakistan","P.O. Box 960, 2458 Duis Road","Champlain","Quebec","7612");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (49,49,"Malta","P.O. Box 258, 3508 Ac Rd.","100 Mile House","BC","906657");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (50,50,"Saint Kitts and Nevis","Ap #558-7394 Purus. Rd.","Charlottetown","PE","36081-09715");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (51,51,"El Salvador","3452 Taciti St.","Beausejour","MB","56843");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (52,52,"United Arab Emirates","P.O. Box 478, 3452 Donec Rd.","Hudson Bay","Saskatchewan","39331");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (53,53,"Bosnia and Herzegovina","Ap #576-6007 Aliquet Avenue","Regina","SK","KL8 1SS");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (54,54,"Djibouti","6068 Consectetuer St.","Batiscan","QC","674702");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (55,55,"Vanuatu","677 Orci Street","Kitchener","Ontario","Z9915");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (56,56,"Guam","3644 Suspendisse Ave","Minitonas","Manitoba","55940-525");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (57,57,"Palau","430-5414 Dolor Road","Montague","PE","1821");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (58,58,"Argentina","P.O. Box 287, 3008 Duis Rd.","Penticton","British Columbia","82215");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (59,59,"Costa Rica","Ap #279-1585 Tincidunt Street","Lakeshore","ON","1657");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (60,60,"Qatar","P.O. Box 582, 5495 Nibh St.","Bay Roberts","NL","71938");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (61,61,"Rwanda","341-3506 Id Rd.","Macklin","SK","85861");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (62,62,"Solomon Islands","P.O. Box 252, 574 Eu Rd.","Wabamun","Alberta","329620");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (63,63,"Saint Lucia","Ap #331-8529 Sed Rd.","Whitehorse","YT","130647");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (64,64,"Norway","5962 Dictum St.","Whitehorse","Yukon","4907 PH");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (65,65,"Panama","Ap #880-7915 Ornare Rd.","Carleton","QC","656789");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (66,66,"Saint Vincent and The Grenadines","888-1909 Sit Road","Pangnirtung","Nunavut","107495");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (67,67,"Andorra","865-7701 Malesuada Rd.","Drayton Valley","Alberta","16837");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (68,68,"American Samoa","P.O. Box 635, 7124 Velit. St.","Enterprise","Northwest Territories","45235");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (69,69,"Niue","714-6353 Quisque Street","Asbestos","Quebec","854596");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (70,70,"Slovenia","Ap #510-1645 Duis Rd.","Arviat","Nunavut","20315");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (71,71,"Tajikistan","Ap #182-8763 Ac St.","Tsiigehtchic","NT","9054");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (72,72,"Virgin Islands, United States","884-8955 Hendrerit St.","Whitehorse","Yukon","26889");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (73,73,"Singapore","P.O. Box 470, 3196 Proin Av.","Fraser Lake","British Columbia","929819");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (74,74,"Germany","Ap #909-3870 Cras St.","Airdrie","Alberta","08997");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (75,75,"Botswana","P.O. Box 473, 1523 Molestie Rd.","Rouyn-Noranda","Quebec","230997");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (76,76,"Dominican Republic","Ap #845-1930 Cum Road","Fort Simpson","Northwest Territories","51506");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (77,77,"Latvia","553-7108 Arcu. St.","Marystown","NL","68-823");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (78,78,"Belgium","P.O. Box 901, 3275 Elit, Rd.","Carbonear","Newfoundland and Labrador","04211");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (79,79,"Congo (Brazzaville)","7963 Laoreet Street","Fort McPherson","NT","98056");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (80,80,"Morocco","3156 Nonummy St.","Paulatuk","Northwest Territories","77757");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (81,81,"Antarctica","668-8497 Arcu St.","Montebello","Quebec","18986");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (82,82,"Angola","P.O. Box 682, 760 Non Street","Lourdes","Manitoba","7269 YA");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (83,83,"Guadeloupe","Ap #359-3240 Cras St.","Gander","Newfoundland and Labrador","6625");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (84,84,"Angola","P.O. Box 575, 3921 Amet, Ave","Gjoa Haven","NU","72490");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (85,85,"Comoros","Ap #981-3687 A, Av.","Bathurst","NB","67352");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (86,86,"Romania","435-2923 Phasellus Avenue","Crystal Springs","Alberta","62376");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (87,87,"Côte D'Ivoire (Ivory Coast)","705-7921 Vivamus Ave","Saskatoon","SK","52260");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (88,88,"Åland Islands","6657 Pharetra. St.","Stratford","Prince Edward Island","8360");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (89,89,"Argentina","Ap #384-5594 Ante Avenue","Fredericton","NB","E9V 9K3");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (90,90,"Barbados","Ap #569-5264 Dolor, Av.","New Glasgow","NS","73809");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (91,91,"Kazakhstan","291 Condimentum. Street","Penhold","AB","50989-66357");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (92,92,"Uruguay","Ap #533-5770 Diam Street","Gjoa Haven","NU","24547");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (93,93,"Morocco","P.O. Box 521, 217 Neque Ave","Mayerthorpe","Alberta","59706");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (94,94,"Botswana","Ap #157-7805 Diam Avenue","Springdale","Newfoundland and Labrador","A7A 5V5");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (95,95,"Mexico","Ap #448-7176 Parturient Avenue","Cariboo Regional District","British Columbia","675660");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (96,96,"Bermuda","409-2185 Eu Av.","Valleyview","AB","00408");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (97,97,"Croatia","734-789 Interdum St.","Yorkton","SK","51100");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (98,98,"Israel","Ap #132-9632 Iaculis St.","Burin","Newfoundland and Labrador","5897");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (99,99,"Madagascar","P.O. Box 834, 2838 Duis Street","Aklavik","Northwest Territories","64824");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (100,100,"Moldova","6210 Hendrerit. St.","Pugwash","Nova Scotia","991315");
# ----------------------------------------------------------
-- Shipping Address
# ----------------------------------------------------------
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (1,1,"Laos","105-7912 Tincidunt Rd.","Winnipeg","Manitoba","359083");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (2,2,"Central African Republic","1517 In Road","Watson Lake","YT","2410 DI");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (3,3,"Tajikistan","6894 Magna. St.","Fort Resolution","Northwest Territories","Z5046");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (4,4,"Seychelles","406 Urna St.","Argyle","Nova Scotia","60318");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (5,5,"Bouvet Island","162-2348 Eu, Ave","Stirling","AB","237597");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (6,6,"Botswana","Ap #391-6045 Orci Rd.","North Bay","Ontario","U6W 7HI");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (7,7,"Brunei","Ap #866-4724 Nec, St.","Duncan","British Columbia","8562");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (8,8,"Guyana","Ap #557-4377 Massa Ave","Eckville","AB","35954");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (9,9,"Gabon","3333 Etiam Road","Bathurst","New Brunswick","354605");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (10,10,"Lebanon","1861 Sed St.","Langenburg","Saskatchewan","14907-389");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (11,11,"Samoa","803 Turpis. Ave","Charlottetown","Prince Edward Island","9517");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (12,12,"Namibia","311-3630 Faucibus. St.","Montague","Prince Edward Island","78334");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (13,13,"Slovenia","P.O. Box 966, 5526 Elit. St.","Stratford","PE","9919 LR");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (14,14,"Barbados","544 Elit, Road","Gibsons","BC","44836");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (15,15,"Saint Pierre and Miquelon","P.O. Box 845, 9096 Libero Avenue","Fogo","NL","25315");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (16,16,"Romania","282-1247 Dui, Road","Argyle","Nova Scotia","690086");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (17,17,"United Arab Emirates","830-5704 Lorem. Street","Lloydminster","Saskatchewan","VF2 9WH");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (18,18,"Guernsey","854-294 Dignissim Avenue","Arviat","Nunavut","492266");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (19,19,"United States","7504 Neque St.","Argyle","Nova Scotia","63498");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (20,20,"Ecuador","7811 Tellus St.","Cantley","QC","80175-43232");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (21,21,"Niue","Ap #528-9432 Velit Ave","Ucluelet","BC","53240");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (22,22,"Cayman Islands","P.O. Box 818, 1279 Libero. Rd.","Stonewall","MB","1055");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (23,23,"South Africa","7540 Semper. Av.","Miramichi","NB","B89 4VO");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (24,24,"Saint Martin","493-7215 Nulla. Rd.","Saint John","NB","Z5697");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (25,25,"Gabon","Ap #636-8726 Rhoncus. Avenue","Campbellton","New Brunswick","3179");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (26,26,"Guinea","P.O. Box 390, 5345 Rutrum Street","Baddeck","Nova Scotia","Z2022");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (27,27,"China","P.O. Box 960, 2034 Dolor St.","Cumberland County","NS","33860");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (28,28,"Micronesia","5140 Egestas Rd.","Campbellton","NB","56980");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (29,29,"France","6512 Tincidunt Avenue","Daly","MB","697182");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (30,30,"Mauritania","3428 Luctus Rd.","Watson Lake","YT","60035");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (31,31,"Ghana","3729 Non Av.","Dieppe","NB","Z4948");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (32,32,"French Southern Territories","8337 Dui Av.","Stonewall","MB","1843");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (33,33,"Bouvet Island","824-6198 Nisl Road","Halifax","Nova Scotia","8697");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (34,34,"Maldives","Ap #285-2980 Ipsum. Rd.","Pangnirtung","NU","Z5028");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (35,35,"Bahamas","851-8820 Eu, Road","Town of Yarmouth","Nova Scotia","40906");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (36,36,"Chile","831-9170 Scelerisque Rd.","Fort Laird","NT","58609");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (37,37,"Guinea","6180 Vitae Ave","Markham","Ontario","10215");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (38,38,"Romania","Ap #915-5521 Sagittis St.","Flin Flon","Manitoba","24333-61242");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (39,39,"Anguilla","3026 Cursus. Road","Town of Yarmouth","NS","184996");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (40,40,"Central African Republic","4572 Dolor Road","Iqaluit","NU","542006");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (41,41,"Pakistan","894-800 Fusce St.","Pangnirtung","Nunavut","6839");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (42,42,"Malawi","P.O. Box 976, 1867 Erat, Rd.","Lloydminster","SK","Z7939");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (43,43,"Jersey","P.O. Box 243, 7477 Ligula. St.","Fredericton","New Brunswick","3532");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (44,44,"Seychelles","925-9133 Nulla Rd.","Irricana","AB","77797");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (45,45,"Jordan","Ap #852-4379 Sapien Ave","Strathcona County","Alberta","63392");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (46,46,"Uzbekistan","Ap #885-887 Nisi Ave","Merrickville-Wolford","ON","12450");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (47,47,"Burkina Faso","7539 Non Avenue","Airdrie","Alberta","07543");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (48,48,"Dominican Republic","802-6318 Orci Rd.","Burin","NL","465299");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (49,49,"Tokelau","Ap #652-8542 Vitae Ave","Whitehorse","Yukon","252054");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (50,50,"Georgia","7963 Ultrices Avenue","Iqaluit","NU","786539");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (51,51,"Tunisia","Ap #207-1031 Lacus. Avenue","Hines Creek","AB","922648");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (52,52,"New Caledonia","P.O. Box 341, 3032 Vestibulum Rd.","Lang","Saskatchewan","7742");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (53,53,"Oman","668-8293 Lorem Street","Charlottetown","Prince Edward Island","175807");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (54,54,"Gabon","9908 Risus. Av.","Annapolis County","NS","19070");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (55,55,"Honduras","160-7451 A Av.","Lakeland County","Alberta","5774");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (56,56,"Syria","483-9112 Sed Avenue","Montague","PE","05638");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (57,57,"Bahrain","719 Non Rd.","Whitehorse","Yukon","QZ0T 9UH");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (58,58,"Ukraine","8859 Orci Ave","Edmundston","NB","125903");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (59,59,"Palau","617-7185 Mi. Ave","Pointe-aux-Trembles","Quebec","70138");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (60,60,"Puerto Rico","9291 Velit Ave","Prince Albert","SK","96112-90016");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (61,61,"Montenegro","2006 Arcu St.","Stratford","PE","C9Y 6G5");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (62,62,"Liechtenstein","8422 Non Ave","High Level","Alberta","182606");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (63,63,"Nepal","P.O. Box 168, 4945 Sit Street","Dieppe","NB","82278");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (64,64,"Nauru","7442 Non Av.","Cape Breton Island","Nova Scotia","725161");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (65,65,"Macedonia","181 Pellentesque Rd.","Etobicoke","ON","78-930");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (66,66,"Andorra","Ap #996-9587 Magnis Avenue","Holman","NT","48155");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (67,67,"Macedonia","P.O. Box 505, 7390 Non, St.","Fermont","QC","35282-015");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (68,68,"Sint Maarten","275-7126 Fringilla St.","Minitonas","Manitoba","21961");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (69,69,"Uganda","P.O. Box 366, 3648 Orci Road","Macklin","SK","90532");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (70,70,"Panama","P.O. Box 596, 1279 Ut St.","Ottawa","ON","37406");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (71,71,"Jordan","5988 Donec Av.","Watson Lake","Yukon","40794-825");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (72,72,"Uruguay","273-7890 Tellus, St.","Stonewall","Manitoba","68581");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (73,73,"United Kingdom (Great Britain)","1850 Libero Ave","Watson Lake","YT","Z8104");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (74,74,"British Indian Ocean Territory","4666 Aliquam Avenue","Argyle","NS","03269");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (75,75,"Philippines","P.O. Box 695, 3964 Blandit Ave","Rivière-du-Loup","Quebec","2116");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (76,76,"Kyrgyzstan","P.O. Box 794, 2869 Eget Ave","Iqaluit","NU","127334");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (77,77,"Ghana","672-6737 Scelerisque Avenue","Fredericton","New Brunswick","674161");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (78,78,"Hong Kong","4446 Rutrum Rd.","Valley East","ON","9239");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (79,79,"Malawi","5815 Dictum Avenue","Whitehorse","Yukon","14137");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (80,80,"Ghana","P.O. Box 811, 2988 Ac Street","Arviat","NU","6886");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (81,81,"Tonga","798-1308 Vitae Street","Arviat","NU","1167 BF");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (82,82,"Curaçao","588-8410 Sem Av.","Marystown","Newfoundland and Labrador","9870");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (83,83,"Swaziland","4036 Ornare, Rd.","Charlottetown","Prince Edward Island","70991");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (84,84,"Philippines","326-7312 Praesent Rd.","St. Thomas","Ontario","95400");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (85,85,"Sweden","P.O. Box 518, 3308 Morbi Avenue","Whitehorse","Yukon","413468");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (86,86,"Aruba","Ap #610-6192 Donec Rd.","Beausejour","Manitoba","3520 UN");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (87,87,"Saudi Arabia","Ap #330-7868 Lectus St.","Marystown","Newfoundland and Labrador","ZE1 6ZK");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (88,88,"Sao Tome and Principe","Ap #224-9511 Semper Av.","Dieppe","New Brunswick","5589 HP");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (89,89,"Tanzania","Ap #965-1105 Leo, Rd.","Hudson Bay","SK","25205");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (90,90,"Saint Barthélemy","Ap #419-6705 Vestibulum, Ave","Estevan","Saskatchewan","6210");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (91,91,"Guam","575-6726 Egestas Street","Marystown","NL","954369");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (92,92,"China","P.O. Box 100, 3402 Sed Av.","Spaniard's Bay","NL","56666-05835");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (93,93,"Svalbard and Jan Mayen Islands","P.O. Box 341, 5841 Consectetuer Ave","Chetwynd","British Columbia","759300");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (94,94,"Finland","P.O. Box 132, 9287 Mollis. Av.","Whitehorse","Yukon","298222");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (95,95,"Marshall Islands","491-3598 Varius Street","Pickering","ON","49122-932");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (96,96,"Ireland","P.O. Box 526, 9733 Dui. Avenue","Outremont","QC","5600");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (97,97,"Palestine, State of","Ap #524-6710 Laoreet Ave","Saskatoon","SK","S8W 4T3");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (98,98,"Saint Martin","P.O. Box 318, 1148 Dolor Rd.","Arviat","NU","26273");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (99,99,"Hong Kong","973-5127 Orci Av.","Aylmer","Quebec","98639");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (100,100,"Somalia","Ap #720-2131 Nisl Street","Port Moody","British Columbia","756675");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (101,101,"Antigua and Barbuda","P.O. Box 484, 1885 Eros. Rd.","Halifax","Nova Scotia","3106 MA");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (102,102,"Cayman Islands","Ap #266-8804 Id Ave","Minitonas","MB","Z5232");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (103,103,"Estonia","Ap #848-2958 Ut Avenue","Gjoa Haven","NU","L2 4CI");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (104,104,"Pakistan","9529 Ornare, Rd.","Baie-Comeau","QC","84989");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (105,105,"Czech Republic","327-7044 Luctus Av.","Paulatuk","NT","P0Q 6PD");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (106,106,"San Marino","4186 Sed Avenue","Miramichi","NB","17081-873");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (107,107,"Micronesia","8905 Nam Rd.","Fort Laird","Northwest Territories","231625");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (108,108,"Saint Vincent and The Grenadines","P.O. Box 811, 5045 Vulputate, Av.","Cap-Rouge","QC","42-623");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (109,109,"Heard Island and Mcdonald Islands","997-3361 Fusce St.","Langenburg","SK","20-456");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (110,110,"Reunion","7473 Vitae Avenue","Ottawa-Carleton","Ontario","1717");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (111,111,"Iran","245-1212 Dui. Rd.","Rae Lakes","NT","77333");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (112,112,"Latvia","Ap #390-4687 Duis St.","Pangnirtung","NU","64-637");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (113,113,"Dominican Republic","239-7363 Neque Ave","Campbellton","New Brunswick","60738");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (114,114,"Honduras","P.O. Box 735, 9664 Lorem, Rd.","Charlottetown","Prince Edward Island","36899");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (115,115,"Bangladesh","766-8260 Nunc Avenue","Charlottetown","PE","09-636");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (116,116,"Pakistan","P.O. Box 277, 9621 Accumsan Road","Pugwash","NS","96621-783");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (117,117,"Nauru","Ap #445-250 Gravida Road","New Sarepta","AB","788446");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (118,118,"Nauru","Ap #292-6296 Phasellus Road","North Vancouver","British Columbia","03143-418");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (119,119,"Solomon Islands","4007 Tincidunt Street","Pangnirtung","Nunavut","35582");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (120,120,"Slovakia","677-1790 Non Av.","Warwick","Ontario","61369");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (121,121,"Belarus","Ap #638-3127 Posuere St.","Winnipeg","Manitoba","95303");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (122,122,"Sierra Leone","P.O. Box 357, 1257 Eu Rd.","Stratford","PE","61086");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (123,123,"Panama","P.O. Box 987, 3781 Sed Road","Iqaluit","NU","X1L 8M6");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (124,124,"Saint Vincent and The Grenadines","935-2673 Mauris St.","White Rock","BC","2029");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (125,125,"Angola","1739 Vel Avenue","Bay Roberts","Newfoundland and Labrador","A0N 8C6");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (126,126,"Mayotte","562-9218 Malesuada Road","Bonnyville Municipal District","AB","5464 HV");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (127,127,"Central African Republic","1404 In St.","Holman","Northwest Territories","902748");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (128,128,"Kazakhstan","929 Risus. St.","Wekweti","NT","998368");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (129,129,"Liberia","P.O. Box 720, 4429 Facilisis St.","Baddeck","Nova Scotia","931915");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (130,130,"Montenegro","6145 Mauris Rd.","Winnipeg","MB","4658");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (131,131,"Grenada","3962 Praesent Road","Langley","British Columbia","417091");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (132,132,"Marshall Islands","337-9018 Sed Street","Montebello","Quebec","975686");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (133,133,"Israel","Ap #530-6046 Nullam Av.","Spruce Grove","Alberta","80323");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (134,134,"Qatar","833-1405 Non Av.","Charlottetown","PE","I4 5FN");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (135,135,"Mauritius","P.O. Box 348, 780 Risus Street","Charlottetown","Prince Edward Island","43344");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (136,136,"Cuba","8891 Morbi St.","Watson Lake","Yukon","124227");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (137,137,"Comoros","Ap #968-7895 Donec Rd.","Whitehorse","YT","719246");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (138,138,"Serbia","Ap #291-2313 Pretium Street","Carstairs","Alberta","68003");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (139,139,"Sao Tome and Principe","Ap #741-3486 Proin Road","Fredericton","NB","500950");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (140,140,"Bahrain","8260 Vivamus Road","Iqaluit","Nunavut","361106");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (141,141,"Comoros","932-4236 Cras St.","Canora","SK","2526 QD");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (142,142,"Australia","3532 Eu Rd.","Edmundston","New Brunswick","58-932");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (143,143,"Eritrea","551-1376 Sem Av.","Bearberry","AB","30712");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (144,144,"Kyrgyzstan","P.O. Box 469, 8253 Mauris Ave","Baie-Saint-Paul","Quebec","16767");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (145,145,"Jersey","Ap #622-7512 Aliquam Av.","Stonewall","MB","06047");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (146,146,"Ethiopia","Ap #182-3195 Facilisis Av.","Harbour Grace","Newfoundland and Labrador","3655");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (147,147,"Nicaragua","2232 Ut, Road","Halifax","NS","4373");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (148,148,"Bolivia","P.O. Box 590, 2006 Tempor Street","Daly","Manitoba","40507-12757");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (149,149,"Tunisia","Ap #650-3752 Tincidunt, Street","Stratford","PE","28940");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (150,150,"Liberia","P.O. Box 951, 5716 Sollicitudin Rd.","Fermont","QC","78873");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (151,151,"Romania","500-2814 Adipiscing Road","Lourdes","Manitoba","440176");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (152,152,"Martinique","2068 Ante Rd.","Hay River","NT","89894");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (153,153,"Kyrgyzstan","3514 Lobortis Ave","McCallum","NL","60211");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (154,154,"Taiwan","P.O. Box 569, 518 Dignissim St.","Whitehorse","Yukon","105649");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (155,155,"Oman","110 Consequat Street","Bathurst","New Brunswick","81351");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (156,156,"Kuwait","598-4382 Tristique Rd.","Whitehorse","Yukon","4432");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (157,157,"Equatorial Guinea","P.O. Box 388, 1785 Turpis. Av.","Fortune","NL","097499");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (158,158,"Somalia","P.O. Box 738, 2979 Lorem Av.","Abbotsford","British Columbia","40719");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (159,159,"Jordan","Ap #872-6715 Consectetuer St.","Stratford","Prince Edward Island","57325");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (160,160,"Marshall Islands","7645 Mus. Rd.","Cambridge Bay","Nunavut","1714");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (161,161,"New Zealand","606-392 Curabitur Rd.","Duncan","British Columbia","V9W 0B9");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (162,162,"Norfolk Island","5747 Posuere Rd.","Lakeshore","ON","20611");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (163,163,"Norway","Ap #797-8928 Facilisis Rd.","Charlottetown","Prince Edward Island","785510");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (164,164,"Swaziland","P.O. Box 648, 9452 Malesuada Rd.","Alert Bay","British Columbia","38216");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (165,165,"Tonga","P.O. Box 368, 2658 Ac St.","Cochrane","Alberta","13468");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (166,166,"Pakistan","3590 Nulla Rd.","Fort Simpson","Northwest Territories","942715");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (167,167,"Vanuatu","P.O. Box 867, 121 Egestas. Street","St. Thomas","ON","504482");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (168,168,"Solomon Islands","822-6216 Nisl Rd.","Gjoa Haven","NU","6013");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (169,169,"Tunisia","Ap #649-8721 Aliquet Ave","Campbellton","New Brunswick","13670");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (170,170,"French Polynesia","6920 Proin Avenue","Miramichi","NB","PF9W 8PV");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (171,171,"Russian Federation","Ap #912-2979 Tempus St.","Pugwash","NS","05319");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (172,172,"Chile","P.O. Box 265, 5698 At, St.","Nelson","BC","60408");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (173,173,"Serbia","Ap #638-1011 Fusce Av.","Winnipeg","Manitoba","01040");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (174,174,"Virgin Islands, British","3344 Felis, Ave","Lourdes","MB","T4 3OW");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (175,175,"Christmas Island","Ap #265-861 Lectus Rd.","Stratford","Prince Edward Island","242415");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (176,176,"Pitcairn Islands","P.O. Box 530, 8217 Pellentesque St.","Lloydminster","AB","11080");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (177,177,"Taiwan","P.O. Box 237, 9467 Aliquam Ave","Langenburg","SK","52-409");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (178,178,"Australia","Ap #857-5295 Sed Street","Trochu","AB","17664");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (179,179,"Bosnia and Herzegovina","Ap #154-9577 Erat Ave","Berwick","NS","Z4281");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (180,180,"Belize","P.O. Box 767, 8379 Vehicula Rd.","Chelsea","QC","90091-38269");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (181,181,"Thailand","Ap #568-4362 Risus. St.","Guysborough","Nova Scotia","07801");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (182,182,"French Polynesia","3985 Eros. Av.","Collines-de-l'Outaouais","Quebec","951596");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (183,183,"Kazakhstan","P.O. Box 695, 4873 Ornare, Street","Greater Sudbury","ON","2869");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (184,184,"Belgium","3726 Aliquet Street","Bay Roberts","NL","F4X 5WJ");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (185,185,"Netherlands","6649 Urna. Street","Iqaluit","Nunavut","784565");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (186,186,"Bhutan","147-1807 Cras Rd.","Trochu","AB","51554-82607");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (187,187,"Ghana","983-7136 Lacinia St.","Guelph","Ontario","5925");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (188,188,"Swaziland","Ap #392-8064 Erat. Ave","Goderich","ON","8075");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (189,189,"Germany","Ap #263-390 Lectus Road","Vaughan","Ontario","37260-60399");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (190,190,"Equatorial Guinea","Ap #482-8768 Natoque Av.","Cap-Rouge","QC","559025");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (191,191,"Norfolk Island","P.O. Box 850, 4738 Dictum. Av.","Yorkton","Saskatchewan","52928");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (192,192,"French Guiana","P.O. Box 978, 3463 Rutrum Ave","Prince Albert","SK","3109");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (193,193,"French Guiana","6622 Mauris St.","Whitehorse","Yukon","95671-39843");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (194,194,"Ireland","Ap #175-3953 Sociis St.","Smoky Lake","AB","4902");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (195,195,"Senegal","Ap #243-2788 Donec St.","Chambord","Quebec","1616");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (196,196,"Canada","P.O. Box 967, 7269 Quam St.","Québec City","QC","852738");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (197,197,"Western Sahara","P.O. Box 487, 2841 Amet Ave","Tumbler Ridge","BC","79765-94982");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (198,198,"Iceland","9823 Adipiscing Av.","Baie-D'Urfé","Quebec","05727");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (199,199,"Liberia","Ap #921-3532 Erat Rd.","Miramichi","New Brunswick","E5X 5Z4");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (200,200,"Saint Pierre and Miquelon","7112 At, Road","Pointe-du-Lac","QC","02955");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (201,201,"Anguilla","4685 Malesuada Road","Campbellton","New Brunswick","7349");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (202,202,"Thailand","564-797 Non, Avenue","Cambridge Bay","NU","32996");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (203,203,"Germany","Ap #617-1167 Arcu Street","Lourdes","Manitoba","050001");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (204,204,"Saint Barthélemy","P.O. Box 444, 9182 Nullam Avenue","Lourdes","Manitoba","92333");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (205,205,"Hong Kong","707 Orci, Ave","Thurso","Quebec","21912");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (206,206,"Jamaica","4089 Pharetra Avenue","Edmundston","New Brunswick","62412");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (207,207,"Antigua and Barbuda","6044 Varius St.","Pincher Creek","AB","Z7495");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (208,208,"San Marino","636-4640 Libero Avenue","Lac-Serent","Quebec","76736");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (209,209,"Seychelles","7999 Gravida Rd.","Watson Lake","Yukon","52277");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (210,210,"Algeria","P.O. Box 144, 9120 Etiam Av.","Iqaluit","NU","021201");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (211,211,"Lebanon","203-7130 Libero Road","Baddeck","NS","B5J 2G2");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (212,212,"Hong Kong","6306 Hendrerit Avenue","Montreal","Quebec","07366-37862");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (213,213,"Barbados","131-5616 Faucibus St.","Watson Lake","YT","818025");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (214,214,"Saudi Arabia","9540 Feugiat St.","Stonewall","MB","22-116");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (215,215,"Saint Helena, Ascension and Tristan da Cunha","1671 Integer Rd.","Moncton","New Brunswick","Z7312");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (216,216,"Rwanda","Ap #734-3093 Turpis. St.","Kitchener","Ontario","3880 JQ");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (217,217,"South Africa","1791 Dignissim Av.","Chilliwack","British Columbia","00094");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (218,218,"Heard Island and Mcdonald Islands","865 Quis Rd.","Langenburg","Saskatchewan","01975-707");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (219,219,"Timor-Leste","P.O. Box 732, 4765 Vel Ave","Arviat","NU","860618");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (220,220,"Seychelles","P.O. Box 320, 3890 Vulputate Avenue","Estevan","SK","819486");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (221,221,"Latvia","5225 Nibh Rd.","Wolfville","Nova Scotia","86-503");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (222,222,"Thailand","661-4490 Erat. Road","New Glasgow","NS","60405");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (223,223,"Kenya","P.O. Box 611, 2740 Dui Avenue","Springdale","Newfoundland and Labrador","41749");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (224,224,"Jersey","Ap #344-5265 Feugiat Road","Canora","SK","869444");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (225,225,"Georgia","Ap #566-9212 Id Rd.","Pangnirtung","NU","84746");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (226,226,"Norway","886-9520 Nulla. St.","Winnipeg","Manitoba","398733");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (227,227,"Palestine, State of","2574 Ut Avenue","Weyburn","Saskatchewan","339153");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (228,228,"Haiti","472-2331 Maecenas Avenue","100 Mile House","BC","9238");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (229,229,"Slovenia","4955 Sed Road","Stratford","Prince Edward Island","537785");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (230,230,"Guinea-Bissau","Ap #703-6604 Consectetuer Road","Burin","NL","7766");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (231,231,"Saint Martin","9332 Eu Ave","Carbonear","Newfoundland and Labrador","XT44 4JV");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (232,232,"Heard Island and Mcdonald Islands","Ap #394-3830 Mauris Rd.","McCallum","Newfoundland and Labrador","9424");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (233,233,"Canada","Ap #383-1811 Proin Street","St. Albert","Alberta","6136 KA");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (234,234,"Guatemala","461-4446 Donec Av.","Belcarra","British Columbia","ZI58 5IM");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (235,235,"France","6308 Scelerisque Av.","Town of Yarmouth","Nova Scotia","664381");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (236,236,"United States Minor Outlying Islands","Ap #903-7667 Adipiscing Road","Wolfville","Nova Scotia","92-167");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (237,237,"Benin","P.O. Box 175, 2114 Nunc St.","Cap-de-la-Madeleine","QC","7949");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (238,238,"Djibouti","358 Enim, St.","Yorkton","SK","684100");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (239,239,"Brunei","947-4119 Scelerisque Road","Collines-de-l'Outaouais","Quebec","4501");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (240,240,"Monaco","P.O. Box 553, 1858 Felis, Av.","Marystown","NL","39749");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (241,241,"Antarctica","422-7841 Eget Av.","Brandon","Manitoba","20187");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (242,242,"Niger","4076 Nec Street","Burin","Newfoundland and Labrador","80977");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (243,243,"Spain","953-3484 Mi. Rd.","Montague","PE","42144");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (244,244,"Uganda","8393 Lobortis. Av.","Enterprise","NT","2715");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (245,245,"Liberia","Ap #263-8195 Non, Ave","Winnipeg","MB","85242");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (246,246,"Austria","224-6362 Mollis Street","Leduc","Alberta","11788");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (247,247,"Netherlands","P.O. Box 683, 4909 Aenean Road","Arviat","NU","649222");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (248,248,"Reunion","Ap #260-3655 Magna Av.","Deline","NT","90570");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (249,249,"Haiti","296-9067 Vitae Road","Lanark County","Ontario","755131");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (250,250,"Slovakia","441-2918 Aliquam St.","Whitehorse","YT","7738");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (251,251,"Cayman Islands","705-7521 Lorem, Street","Whitehorse","Yukon","37921");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (252,252,"Paraguay","Ap #765-8086 Sit Avenue","Dawson Creek","British Columbia","5866 JL");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (253,253,"Cameroon","5279 Nunc St.","Yorkton","SK","S5G 1C3");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (254,254,"Angola","Ap #423-5562 Penatibus Avenue","Caledon","Ontario","3033");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (255,255,"Denmark","5258 Tellus. Rd.","Ottawa-Carleton","Ontario","6820");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (256,256,"Bhutan","548-2370 Metus Ave","Fermont","QC","45459");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (257,257,"Panama","Ap #896-2102 Nisl Road","Town of Yarmouth","NS","70-532");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (258,258,"American Samoa","Ap #479-281 Nascetur Street","Fort Resolution","Northwest Territories","586117");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (259,259,"Moldova","P.O. Box 664, 911 Bibendum Rd.","Halifax","NS","93773");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (260,260,"Yemen","897-9986 Semper Rd.","Fogo","Newfoundland and Labrador","965851");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (261,261,"Iceland","P.O. Box 489, 5499 Consectetuer St.","Lac La Biche County","AB","78769");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (262,262,"Viet Nam","P.O. Box 717, 8684 Primis Ave","Kakisa","Northwest Territories","5720");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (263,263,"Syria","5709 Donec Road","Gander","Newfoundland and Labrador","7852");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (264,264,"Guinea","3273 Tristique Rd.","Lac Ste. Anne","Alberta","7871");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (265,265,"Botswana","Ap #405-2762 Aliquam Rd.","Canora","SK","58483");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (266,266,"United Kingdom (Great Britain)","9071 In St.","Baddeck","Nova Scotia","22871");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (267,267,"Czech Republic","8655 Et St.","Owen Sound","Ontario","35611");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (268,268,"Nepal","7382 Egestas. Av.","Annapolis Royal","Nova Scotia","153298");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (269,269,"France","P.O. Box 288, 6843 Scelerisque St.","Bonavista","NL","30105");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (270,270,"Heard Island and Mcdonald Islands","P.O. Box 862, 9387 Malesuada Rd.","Canmore","AB","768971");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (271,271,"Mauritania","8766 Non, St.","Stonewall","MB","Z5225");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (272,272,"Malta","P.O. Box 381, 4608 Et Avenue","Oxford County","Ontario","521936");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (273,273,"Belgium","P.O. Box 768, 4823 Arcu Avenue","Watson Lake","YT","9751");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (274,274,"American Samoa","P.O. Box 742, 6266 Vivamus St.","Saskatoon","Saskatchewan","9319 DB");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (275,275,"Antarctica","6331 Nunc Rd.","Blind River","ON","86999");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (276,276,"Chile","593-4822 Neque Road","Guysborough","NS","52926");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (277,277,"Kenya","P.O. Box 180, 289 Mollis. Rd.","Airdrie","AB","WF62 2YD");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (278,278,"Denmark","Ap #270-6181 Molestie St.","Asbestos","QC","5454");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (279,279,"Dominican Republic","P.O. Box 320, 5955 Ridiculus Street","Winnipeg","Manitoba","50-819");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (280,280,"El Salvador","P.O. Box 399, 656 Accumsan Ave","Legal","AB","N00 0OL");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (281,281,"Georgia","410-7452 Venenatis Av.","Annapolis County","NS","619181");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (282,282,"Antarctica","Ap #787-1212 Enim. Road","Bonavista","Newfoundland and Labrador","028007");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (283,283,"Trinidad and Tobago","P.O. Box 661, 8718 Ac Rd.","Watson Lake","Yukon","26426");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (284,284,"Gambia","P.O. Box 703, 9803 Massa. Rd.","Whitehorse","Yukon","8689");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (285,285,"Romania","P.O. Box 233, 6144 Nec, Rd.","Rigolet","NL","A3S 9S1");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (286,286,"Bahamas","569-3403 Suspendisse Avenue","Arviat","NU","04817");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (287,287,"Tunisia","7360 In Street","Dieppe","New Brunswick","452411");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (288,288,"British Indian Ocean Territory","243-4275 Amet St.","Annapolis County","Nova Scotia","90674");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (289,289,"Taiwan","P.O. Box 354, 1657 Sit Rd.","Bathurst","NB","07580-938");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (290,290,"Monaco","626-7987 Egestas St.","Fortune","Newfoundland and Labrador","A3B 5H0");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (291,291,"Brunei","4081 Mattis. Avenue","Mount Pearl","NL","149770");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (292,292,"United States","306-8404 Phasellus Av.","Iqaluit","NU","3737");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (293,293,"Guernsey","5981 Quisque Avenue","Whitehorse","Yukon","7891");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (294,294,"Greenland","595-861 Est Avenue","Charlottetown","PE","51846");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (295,295,"Guatemala","685-584 Nisi. Rd.","Edmundston","NB","294757");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (296,296,"Moldova","P.O. Box 124, 4214 Nullam St.","Charny","Quebec","30404");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (297,297,"Venezuela","P.O. Box 293, 6663 Tempor Av.","Cape Breton Island","Nova Scotia","97798-509");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (298,298,"Mali","P.O. Box 104, 4426 Ligula Street","Burin","Newfoundland and Labrador","04683");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (299,299,"American Samoa","P.O. Box 246, 2210 Nulla. Av.","Flin Flon","Manitoba","22275");
INSERT INTO shipping_address (shipping_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (300,300,"Japan","P.O. Box 306, 1410 Mattis. Rd.","Paradise","NL","59488");




