# ----------------------------------------------------------
-- Billing Address
# ----------------------------------------------------------

INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (1,1,"Laos","6541 Auctor. Avenue","Stonewall","Manitoba","613102");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (2,2,"Poland","7138 Duis St.","Argyle","Nova Scotia","69-560");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (3,3,"Israel","P.O. Box 375, 5193 Porttitor Avenue","Kakisa","NT","384932");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (4,4,"Mauritius","Ap #615-6432 Lacinia Av.","Charlottetown","PE","20413");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (5,5,"Guadeloupe","380-6406 Sed Road","Vancouver","BC","30015");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (6,6,"Armenia","Ap #848-1006 Nullam Avenue","Strathcona County","Alberta","35049");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (7,7,"Tuvalu","P.O. Box 804, 2900 Leo. Ave","Fredericton","NB","838105");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (8,8,"Ghana","521-1969 Semper, St.","East Gwillimbury","Ontario","29897");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (9,9,"Slovakia","1169 Nec, Ave","Edmundston","New Brunswick","112246");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (10,10,"Indonesia","316-1561 Egestas. Road","Montague","Prince Edward Island","0916 UU");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (11,11,"Holy See (Vatican City State)","881-7068 Est Rd.","Whitehorse","YT","P71 6TX");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (12,12,"Virgin Islands, British","P.O. Box 951, 1069 Venenatis Avenue","Lang","SK","68976");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (13,13,"Congo, the Democratic Republic of the","9302 Phasellus Rd.","Stratford","Prince Edward Island","5491");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (14,14,"Kyrgyzstan","2158 Penatibus Av.","Paradise","NL","79413");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (15,15,"Serbia","Ap #446-804 Enim Road","Minitonas","MB","42079");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (16,16,"Tuvalu","Ap #198-1536 Mi Rd.","Inuvik","NT","18817");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (17,17,"Andorra","Ap #439-5167 In Avenue","McCallum","Newfoundland and Labrador","45314");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (18,18,"Puerto Rico","7571 Hendrerit. St.","Iqaluit","Nunavut","5445");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (19,19,"Comoros","173-4592 Nulla Rd.","Berwick","NS","71668");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (20,20,"France","9940 Hendrerit Avenue","Fogo","NL","2334");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (21,21,"Thailand","5782 Ultrices, Road","Arviat","Nunavut","B5 5MB");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (22,22,"Viet Nam","527-4845 Sed Road","Lang","SK","31324");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (23,23,"Korea, North","520-8477 Maecenas Street","Wilmont","ON","879369");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (24,24,"American Samoa","898-3742 Phasellus St.","Richmond","QC","J1P 2V1");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (25,25,"Bermuda","715-4024 Lacinia Rd.","Winnipeg","MB","3559 VZ");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (26,26,"Denmark","531-4366 Nulla St.","Matagami","QC","2235");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (27,27,"Brazil","Ap #265-6088 Feugiat Rd.","Lourdes","Manitoba","88141-38313");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (28,28,"Kuwait","8700 Ante Rd.","Dieppe","NB","860777");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (29,29,"Nicaragua","Ap #389-1647 Felis Street","Canora","Saskatchewan","8436");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (30,30,"Cook Islands","P.O. Box 568, 2381 Velit. St.","Canora","Saskatchewan","3020");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (31,31,"Romania","Ap #763-8780 Enim. Rd.","Whitehorse","YT","22308");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (32,32,"Jamaica","Ap #444-2509 Donec Street","Weyburn","SK","00084");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (33,33,"Nauru","P.O. Box 792, 5412 Cras Av.","Iqaluit","Nunavut","839881");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (34,34,"Zambia","Ap #736-8262 Vehicula. Rd.","Langenburg","SK","51345");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (35,35,"Reunion","764-9317 Mauris St.","Pangnirtung","Nunavut","62114");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (36,36,"Malaysia","7332 Adipiscing Rd.","Maple Creek","Saskatchewan","04128");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (37,37,"Uruguay","258-2777 Amet, Ave","Regina","SK","29349");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (38,38,"Liechtenstein","Ap #376-1474 Mauris St.","Fortune","Newfoundland and Labrador","11664");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (39,39,"Puerto Rico","572-9297 Mollis St.","Baddeck","NS","53286");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (40,40,"Costa Rica","Ap #329-7645 Fringilla, Av.","Welland","ON","848270");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (41,41,"Egypt","Ap #661-8978 Cursus Street","Kent","BC","71517");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (42,42,"Estonia","568-1744 Suscipit, Rd.","Arviat","Nunavut","87612");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (43,43,"Malaysia","Ap #618-1624 Nibh. St.","St. Catharines","Ontario","836930");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (44,44,"Antarctica","P.O. Box 786, 7107 Mauris Street","Cambridge Bay","Nunavut","5082 GK");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (45,45,"Brazil","680-9743 Sagittis Rd.","Penticton","BC","69887-38017");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (46,46,"Virgin Islands, British","242-8761 Molestie Av.","McCallum","Newfoundland and Labrador","543723");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (47,47,"Djibouti","312 Pharetra Rd.","Lang","SK","18579");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (48,48,"Pakistan","P.O. Box 960, 2458 Duis Road","Champlain","Quebec","7612");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (49,49,"Malta","P.O. Box 258, 3508 Ac Rd.","100 Mile House","BC","906657");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (50,50,"Saint Kitts and Nevis","Ap #558-7394 Purus. Rd.","Charlottetown","PE","36081-09715");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (51,51,"El Salvador","3452 Taciti St.","Beausejour","MB","56843");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (52,52,"United Arab Emirates","P.O. Box 478, 3452 Donec Rd.","Hudson Bay","Saskatchewan","39331");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (53,53,"Bosnia and Herzegovina","Ap #576-6007 Aliquet Avenue","Regina","SK","KL8 1SS");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (54,54,"Djibouti","6068 Consectetuer St.","Batiscan","QC","674702");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (55,55,"Vanuatu","677 Orci Street","Kitchener","Ontario","Z9915");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (56,56,"Guam","3644 Suspendisse Ave","Minitonas","Manitoba","55940-525");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (57,57,"Palau","430-5414 Dolor Road","Montague","PE","1821");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (58,58,"Argentina","P.O. Box 287, 3008 Duis Rd.","Penticton","British Columbia","82215");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (59,59,"Costa Rica","Ap #279-1585 Tincidunt Street","Lakeshore","ON","1657");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (60,60,"Qatar","P.O. Box 582, 5495 Nibh St.","Bay Roberts","NL","71938");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (61,61,"Rwanda","341-3506 Id Rd.","Macklin","SK","85861");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (62,62,"Solomon Islands","P.O. Box 252, 574 Eu Rd.","Wabamun","Alberta","329620");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (63,63,"Saint Lucia","Ap #331-8529 Sed Rd.","Whitehorse","YT","130647");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (64,64,"Norway","5962 Dictum St.","Whitehorse","Yukon","4907 PH");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (65,65,"Panama","Ap #880-7915 Ornare Rd.","Carleton","QC","656789");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (66,66,"Saint Vincent and The Grenadines","888-1909 Sit Road","Pangnirtung","Nunavut","107495");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (67,67,"Andorra","865-7701 Malesuada Rd.","Drayton Valley","Alberta","16837");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (68,68,"American Samoa","P.O. Box 635, 7124 Velit. St.","Enterprise","Northwest Territories","45235");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (69,69,"Niue","714-6353 Quisque Street","Asbestos","Quebec","854596");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (70,70,"Slovenia","Ap #510-1645 Duis Rd.","Arviat","Nunavut","20315");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (71,71,"Tajikistan","Ap #182-8763 Ac St.","Tsiigehtchic","NT","9054");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (72,72,"Virgin Islands, United States","884-8955 Hendrerit St.","Whitehorse","Yukon","26889");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (73,73,"Singapore","P.O. Box 470, 3196 Proin Av.","Fraser Lake","British Columbia","929819");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (74,74,"Germany","Ap #909-3870 Cras St.","Airdrie","Alberta","08997");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (75,75,"Botswana","P.O. Box 473, 1523 Molestie Rd.","Rouyn-Noranda","Quebec","230997");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (76,76,"Dominican Republic","Ap #845-1930 Cum Road","Fort Simpson","Northwest Territories","51506");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (77,77,"Latvia","553-7108 Arcu. St.","Marystown","NL","68-823");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (78,78,"Belgium","P.O. Box 901, 3275 Elit, Rd.","Carbonear","Newfoundland and Labrador","04211");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (79,79,"Congo (Brazzaville)","7963 Laoreet Street","Fort McPherson","NT","98056");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (80,80,"Morocco","3156 Nonummy St.","Paulatuk","Northwest Territories","77757");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (81,81,"Antarctica","668-8497 Arcu St.","Montebello","Quebec","18986");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (82,82,"Angola","P.O. Box 682, 760 Non Street","Lourdes","Manitoba","7269 YA");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (83,83,"Guadeloupe","Ap #359-3240 Cras St.","Gander","Newfoundland and Labrador","6625");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (84,84,"Angola","P.O. Box 575, 3921 Amet, Ave","Gjoa Haven","NU","72490");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (85,85,"Comoros","Ap #981-3687 A, Av.","Bathurst","NB","67352");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (86,86,"Romania","435-2923 Phasellus Avenue","Crystal Springs","Alberta","62376");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (87,87,"Côte D'Ivoire (Ivory Coast)","705-7921 Vivamus Ave","Saskatoon","SK","52260");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (88,88,"Åland Islands","6657 Pharetra. St.","Stratford","Prince Edward Island","8360");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (89,89,"Argentina","Ap #384-5594 Ante Avenue","Fredericton","NB","E9V 9K3");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (90,90,"Barbados","Ap #569-5264 Dolor, Av.","New Glasgow","NS","73809");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (91,91,"Kazakhstan","291 Condimentum. Street","Penhold","AB","50989-66357");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (92,92,"Uruguay","Ap #533-5770 Diam Street","Gjoa Haven","NU","24547");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (93,93,"Morocco","P.O. Box 521, 217 Neque Ave","Mayerthorpe","Alberta","59706");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (94,94,"Botswana","Ap #157-7805 Diam Avenue","Springdale","Newfoundland and Labrador","A7A 5V5");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (95,95,"Mexico","Ap #448-7176 Parturient Avenue","Cariboo Regional District","British Columbia","675660");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (96,96,"Bermuda","409-2185 Eu Av.","Valleyview","AB","00408");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (97,97,"Croatia","734-789 Interdum St.","Yorkton","SK","51100");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (98,98,"Israel","Ap #132-9632 Iaculis St.","Burin","Newfoundland and Labrador","5897");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (99,99,"Madagascar","P.O. Box 834, 2838 Duis Street","Aklavik","Northwest Territories","64824");
INSERT INTO billing_address (billing_address_id,customer_id,country,street_name,city_name,state_name,zip_code) VALUES (100,100,"Moldova","6210 Hendrerit. St.","Pugwash","Nova Scotia","991315");
